### ISSUE TITLE
delete_returning doesn't delete the foreign/one-to-one keys

### ISSUE THREAD

**Issue by Abdullah0297445** [M1hacka/django-pg-returning#23]
**Environment:**

Python=3.8
django=3.1
djangorestframework=3.11.1
django-pg-returning=1.3.0

**How to reproduce this error:**

Create any model. Add One-to-one field for this model in another model.
Try to delete any record from the parent model.
It throws an Integrity error.

**My Django View(which causes the error):**

```
@api_view(['POST', ])
@permission_classes([IsAuthenticated, ])
@authentication_classes([SafeJWTAuthentication, ])
def delete_one_or_more_jobs(request):
    """Deletes one or more jobs"""

    if not is_list_of_strings(request.data):
        raise exceptions.ParseError("This API requires a list of one or more Job IDs in the request body.")

    for id in request.data:
        uuid_validation(id)

    tenant = tenant_getter_v2(request, qp=True)

    affected_jobs = Job.objects.filter(tenant=tenant, id__in=request.data).delete_returning()
    affected_jobs = affected_jobs.values_list('id', flat=True)
    return Response(affected_jobs)
```

**Traceback:**

```
Internal Server Error: /api/v1/job/delete/
app_1            | Traceback (most recent call last):
app_1            |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 242, in _commitapp_1            |     return self.connection.commit()
app_1            | psycopg2.errors.ForeignKeyViolation: update or delete on table "job" violates foreign key constraint "job_pipeline_job_id_d60ec84d_fk_job_id" on table "job_pipeline"
app_1            | DETAIL:  Key (id)=(f39a30d3-05b4-4597-a7ab-e2ca92b4ac4a) is still referenced from table "job_pipeline".
app_1            |
app_1            |
app_1            | The above exception was the direct cause of the following exception:
app_1            |
app_1            | Traceback (most recent call last):
app_1            |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
app_1            |     response = get_response(request)
app_1            |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
app_1            |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
app_1            |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
app_1            |     return view_func(*args, **kwargs)
app_1            |   File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
app_1            |     return self.dispatch(request, *args, **kwargs)
app_1            |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
app_1            |     response = self.handle_exception(exc)
app_1            |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
app_1            |     self.raise_uncaught_exception(exc)
app_1            |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
app_1            |     raise exc
app_1            |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
app_1            |     response = handler(request, *args, **kwargs)
app_1            |   File "/usr/local/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
app_1            |     return func(*args, **kwargs)
app_1            |   File "/home/hirecinch-backend/jobs/views.py", line 392, in delete_one_or_more_jobs
app_1            |     affected_jobs = Job.objects.filter(tenant=tenant, id__in=request.data).delete_returning()
app_1            |   File "/usr/local/lib/python3.8/site-packages/django_pg_returning/manager.py", line 183, in delete_returning
app_1            |     return self._get_returning_qs(sql.DeleteQuery)
app_1            |   File "/usr/local/lib/python3.8/site-packages/django_pg_returning/manager.py", line 145, in _get_returning_qs
app_1            |     return self._execute_sql(query, fields)
app_1            |   File "/usr/local/lib/python3.8/site-packages/django_pg_returning/manager.py", line 109, in _execute_sql
app_1            |     return ReturningQuerySet(query_sql, model=self.model, params=query_params, using=using,
app_1            |   File "/usr/local/lib/python3.8/site-packages/django/db/transaction.py", line 232, in __exit__
app_1            |     connection.commit()
app_1            |   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
app_1            |     return func(*args, **kwargs)
app_1            |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 266, in commit
app_1            |     self._commit()
app_1            |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 242, in _commitapp_1            |     return self.connection.commit()
app_1            |   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
app_1            |     raise dj_exc_value.with_traceback(traceback) from exc_value
app_1            |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 242, in _commitapp_1            |     return self.connection.commit()
app_1            | django.db.utils.IntegrityError: update or delete on table "job" violates foreign key constraint "job_pipeline_job_id_d60ec84d_fk_job_id" on table "job_pipeline"
app_1            | DETAIL:  Key (id)=(f39a30d3-05b4-4597-a7ab-e2ca92b4ac4a) is still referenced from table "job_pipeline".
app_1            |
app_1            | [01/Jan/2021 05:59:15] "POST /api/v1/job/delete/?subdomain_prefix=test-1 HTTP/1.1" 500 145088
```

**Comment by M1ha-Shvn** [comment]
Hi, @Abdullah0297445.
Thanks for your report.
Originally, this library has not been designed for complex recursive manipulations. It's purpose is to make effective one-level queries returning the result. It's more like django's [`QuerySet.update(**updates) method`](https://docs.djangoproject.com/en/3.1/ref/models/querysets/#django.db.models.query.QuerySet.update) which doesn't emit any signals or procedures like [`Model.save() method`](https://docs.djangoproject.com/en/3.1/ref/models/instances/#django.db.models.Model.save) does.
Though I can have a look later, if recursive deletes can be implemented.

**Comment by Abdullah0297445** [comment]
oh alright got it. Okay then. Thank you for the response :)

**Comment by M1ha-Shvn** [comment]
Recursive operations combined with returning also leave some unobvious questions: 

1. Should I return only called model results or also those, which were deleted recursively?
2. How to ask for submodel field using only/defer/values methods?
3. How to return results: with single `ReturningQuerySet`  or a list/tuple/dict of QuerySet? May be should look int django's `QuerySet.delete()` implementation.
4. If I change structure returned, how to leave everything back compatible?

P. s. I write it here, for future me =)

**Comment by M1ha-Shvn** [comment]
Decided not to implement this as there are a lot of questions in realisation and also it requires difficult inside logic.
