### ISSUE TITLE
Compatibility with django 4.0+

### ISSUE THREAD

**Issue by M1ha-Shvn** [M1hacka/django-pg-returning#30]
From [django-clickhouse issue](https://github.com/carrotquest/django-clickhouse/issues/47).

Incompatible with django 4.0+
```
Error
Traceback (most recent call last):
  File "/opt/project/tests/test_models.py", line 235, in test_bulk_create_returning
    items = self.django_model.objects.bulk_create_returning(items)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django_pg_returning/manager.py", line 204, in bulk_create_returning
    result = self.bulk_create(objs, batch_size=batch_size)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/project/src/django_clickhouse/models.py", line 101, in bulk_create
    objs = super().bulk_create(objs, batch_size=batch_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 816, in bulk_create
    returned_columns = self._batched_insert(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1817, in _batched_insert
    self._insert(
  File "/usr/local/lib/python3.11/site-packages/django_pg_returning/manager.py", line 37, in _insert
    return_fields = self._get_fields(ignore_deferred=(django.VERSION < (1, 10)))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django_pg_returning/manager.py", line 82, in _get_fields
    self.query.deferred_to_data(fields, self._get_loaded_field_cb)
TypeError: Query.deferred_to_data() takes 2 positional arguments but 3 were given


```

**Comment by M1ha-Shvn** [comment]
Released v2.0.1
